### ISSUE TITLE
Channel closed errors

### ISSUE THREAD

**Issue by PissedCapslock** [TijlB99/tsd#4]
Trying this on a large docu.json file results in a bunch of the following errors.
```events.js:187
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:678:16)
    at reportSuccess (/home/rstevens/code/tsd/node_modules/jest-worker/build/workers/processChild.js:83:11)
    at tryCatcher (/home/rstevens/code/tsd/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/rstevens/code/tsd/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/rstevens/code/tsd/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/rstevens/code/tsd/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/rstevens/code/tsd/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/rstevens/code/tsd/node_modules/bluebird/js/release/promise.js:673:18)
    at MappingPromiseArray.PromiseArray._resolve (/home/rstevens/code/tsd/node_modules/bluebird/js/release/promise_array.js:127:19)
    at MappingPromiseArray._promiseFulfilled (/home/rstevens/code/tsd/node_modules/bluebird/js/release/map.js:108:18)
    at Promise._settlePromise (/home/rstevens/code/tsd/node_modules/bluebird/js/release/promise.js:609:26)
    at Promise._settlePromise0 (/home/rstevens/code/tsd/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/rstevens/code/tsd/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/rstevens/code/tsd/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/rstevens/code/tsd/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/rstevens/code/tsd/node_modules/bluebird/js/release/async.js:102:5)
Emitted 'error' event on process instance at:
    at internal/child_process.js:682:35
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

Perhaps I'm using an invalid input file, but the error message gives me no clue at all about what might be wrong with it.

**Comment by TijlB99** [comment]
It seems like the problem is that comments contain text similar to the following: "shape.Polygon[<3, 3>, <3, 9>, <9, 9>, <9, 3>]". html-react-parser however seems to think these are HTML tags due to the <>, as that makes no sense, it throws an error. Not sure how to fix yet.

**Comment by PissedCapslock** [comment]
Ah good catch.
Perhaps you need to do some escaping before passing it to the parser.
I assume you select the string from the JSON file somewhere, and parse it to the parser. If you can first do some operations on the string, you should be able to avoid this.

**Comment by TijlB99** [comment]
Issue fixed using [sanitize-html](https://www.npmjs.com/package/sanitize-html).
